[package]
name = "chess"
version = "0.1.0"
authors = ["CTHULHU-Jesus <endercreeper92@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
